package com.moviewatchlist.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity class representing a movie stored in the database.
 * <p>
 * This class maps to the "movies" table and contains basic attributes
 * such as title, director, year, genre, watched flag, rating, and image path.
 * <p>
 * Used by the JPA/Hibernate framework for persistence.
 */
@Entity
@Table(name = "movies")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Movie {

    /**
     * Unique identifier for the movie.
     * Automatically generated by the database (auto-increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the movie.
     */
    private String title;

    /**
     * The year the movie was released.
     */
    private String release_year;

    /**
     * The name of the movie's director.
     */
    private String director;

    /**
     * The genre(s) of the movie.
     */
    private String genre;

    /**
     * Indicates whether the user has watched the movie.
     */
    private boolean watched;

    /**
     * The user's rating of the movie (typically 1 to 5).
     */
    private int rating;

    /**
     * Path to the saved image file for the movie (poster or related visual).
     */
    private String imagePath;
}
